controllers/FormController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Form;
use app\models\FormSearch;
use app\models\FormItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FormController implements the CRUD actions for Form model.
 */
class FormController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Form models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FormSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Form model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Form model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Form();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Form model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $formItemSearchModel = new FormItemSearch();
        $formItemDataProvider = $formItemSearchModel->search(Yii::$app->request->queryParams);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'formItemSearchModel' => $formItemSearchModel,
                'formItemDataProvider' => $formItemDataProvider,
            ]);
        }
    }

    /**
     * Deletes an existing Form model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Form model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Form the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Form::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/FormItemController.php
<?php

namespace app\controllers;

use Yii;
use app\models\FormItem;
use app\models\FormItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FormItemController implements the CRUD actions for FormItem model.
 */
class FormItemController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all FormItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FormItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single FormItem model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new FormItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new FormItem();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return;
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing FormItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $element_id
     * @return mixed
     */
    public function actionUpdate($element_id)
    {
        $model = $this->findModel($element_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return;
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing FormItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $element_id
     * @return mixed
     */
    public function actionDelete($element_id)
    {
        $this->findModel($element_id)->delete();

        return;
    }

    /**
     * Finds the FormItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return FormItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = FormItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/form/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Form */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <? // = $form->field($model, 'action')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Создать') : Yii::t('app', 'Обновить'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/form/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Form */

$this->title = Yii::t('app', 'Создать форму');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Формы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="form-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/form/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\FormSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Формы');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="form-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Создать новую форму'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
            // 'action',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/form/update.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Form */

$this->title = 'Обновление данных ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Формы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Обновить');
?>
<div class="form-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
<div class="form-index">
    <h2>Элементы формы</h2>
    <?= Modal::widget([
        'id' => 'item-modal',
        'size' => 'modal-lg',
        'toggleButton' => [
            'label' => 'Добавить элемент',
            'tag' => 'button',
            'class' => 'btn btn-primary',
            'data-target' => '#item-modal',
            'href' => Url::toRoute(['/form-item/create']),
        ],
        'clientOptions' => false,
    ]); ?><br><br>
    <?php Pjax::begin(); ?>    <?= GridView::widget([
        'id' => 'elements',
        'dataProvider' => $formItemDataProvider,
        'filterModel' => $formItemSearchModel,
        'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

            'tag',
            'type',
            'sort',
            'name',
            'label',
            'class',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'delete' => function ($url, $model, $key) {
                        $url = Yii::$app->getUrlManager()->createUrl(['form-item/delete','element_id'=>$key]);
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'class' => 'delete-item-link',
                            'title' => 'Удалить элемент',
                            'aria-label' => 'Удалить элемент',
                            'data-method' => 'post',
                        ]);
                    },
                    'update' => function ($url, $model, $key) {
                        $url = Yii::$app->getUrlManager()->createUrl(['form-item/update','element_id'=>$key]);
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'class' => 'update-item-link',
                            'title' => 'Обновить элемент',
                            'aria-label' => 'Обновить элемент',
                            'data-method' => 'post',
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
    </div>
<?php
Modal::begin([
    'id' => 'modal-update',
    'size' => 'modal-lg',
    'header' => '',
]);
echo Html::tag('div','', [
    'id' => 'update-item',
]);
Modal::end();
$this->registerJs(<<<JS

jQuery('#item-modal').on('click', '.form-item-create', function() {
    jQuery('#formitem-form_id').val('$model->id');
});

jQuery('.form-index').on('click', '.update-item-link', function() {
    var link = jQuery(this).attr('href');
    jQuery.ajax({
        url: link,
        success: function(response) {
            jQuery('#update-item').html(response);
            jQuery('#modal-update').modal('show');
        },        
    });
    return false;
});

jQuery('.form-index').on('click', '.delete-item-link', function() {
    if (confirm('Вы уверены, что хотите удалить элемент?')) {
        var link = jQuery(this).attr('href');
        jQuery.ajax({
            url: link,
            type: 'post',
            success: function(response) {
                jQuery('#elements').yiiGridView('applyFilter');
            },        
        });
    }
    return false;
});
JS
);
$this->registerCss(<<<CSS
.form-item-create {
    margin: 20px;
}
.modal-header {
    display: none;
}
CSS
);

views/form/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Form */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Формы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="form-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Обновить и добавить элементы'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Удалить'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php
    /* не будем отображать пустую форму */
    if (count($model->formItems) > 0) {
        /* пройдем по всем элементам и составим форму */
        $html = "<h3>Форма {$model->name}</h3>";
        foreach ($model->formItems as $element) {
            if ($element->tag == 'input' || $element->tag == 'textarea') {

                if (!empty($element->label)) {
                    $html .= Html::label($element->label);
                }

                $class = '';
                if (!empty($element->class)) {
                    $class = $element->class;
                } else {
                    if ($element->type !== 'checkbox') {
                        $class = 'form-control';
                    }
                }

                $html .= Html::tag($element->tag, '', [
                    'type' => $element->type,
                    'name' => $element->name,
                    'class' => $class,
                ]);
            } elseif ($element->tag == 'button') {

                if (!empty($element->label)) {
                    $label = $element->label;
                } else {
                    $label = 'Кнопка';
                }

                $html .= Html::tag($element->tag, $label, [
                    'type' => $element->type,
                    'name' => $element->name,
                    'class' => !empty($element->class) ? $element->class : 'btn btn-primary',
                ]);
            }
            $html .= '<br>';
        }
        echo Html::beginForm('');
        echo $html;
        echo Html::endForm();
    }
    ?>
</div>